### ISSUE TITLE
Core: Destroy server if first start is unsuccessful

### ISSUE THREAD

**Issue by Igazine** [Moonshine-IDE/Super.Human.Installer#50]
Destroy server automatically if first start is unsuccessful

**Comment by Igazine** [comment]
Stop server automatically if it starts with an error

**Comment by JoelProminic** [comment]
As discussed during the meeting today, this issue may cause some trouble for @MarkProminic and me when debugging issues with the Vagrant scripts.  One tool we have for debugging is to `vagrant ssh` into the VM and rerun the failing command or check the status.  We will probably want a flag  to disable this functionality.

I think this behavior makes sense for general users.  We have seen issues before with users reporting provisioning errors for a partially provisioned instance.

It is good to keep separate logic for the cases when the VM has already been fully provisioned (#53).  We don't want to delete a VM that the user has been testing on because of a temporary issue with the startup actions.

I'm tagging @JustinProminic in case he has more thoughts on this.
