### ISSUE TITLE
Update to demo-tasks v0.1.20

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Installer#77]
During the discussion of #76 today, we also discussed the process for switching to [demo-tasks v0.1.12](https://github.com/DominoVagrant/demo-tasks/releases/tag/demo-tasks%2Fv0.1.20).

From my initial understanding, we need to:
- Copy the demo-tasks files to a new directory [here](https://github.com/Moonshine-IDE/Super.Human.Installer/tree/master/Assets/provisioners/demo-tasks);
- Convert the [updated Hosts.yml](https://github.com/DominoVagrant/demo-tasks/blob/demo-tasks/v0.1.18/Hosts.yml#L125) to a new Hosts.yml.template, matching the insertion parameters [here](https://github.com/Moonshine-IDE/Super.Human.Installer/blob/master/Assets/provisioners/demo-tasks/0.1.17/templates/Hosts.template.yml)
    - Note that some of the task names have changed, to better match the Ansible connections
    - Make sure to preserve any additions to the template, for example the `vars` added for #76.
    - Identify any new required insertion parameters.
- Add code to populate the new insertion parameters

We'll want to review the Hosts.yml changes with @MarkProminic, to determine what is actually needed for Super.Human.Installer.  For example we may be able to remove some of the `port_forwards` properties ([example](https://github.com/DominoVagrant/demo-tasks/blob/9315d44a40a129f03050aaf6f8151a4dd9c55047/Hosts.yml#L162-L172)).

There may also be additional changes required for this.   I remember Tamas was concerned about needing major code refactoring to handle the updated names in the Ansible scripts.

Since this could be a major refactoring, I have assigned it to a separate milestone for now.

**Comment by MarkProminic** [comment]
I will copy the current Hosts.template.yml into demo-tasks, in the same directory as Hosts.yml, and amend it with new variables in the vars block to give greater exposure to the variables that can be changed, that will override the defaults in which the build of SHI was targeted for.  

This should allow the build process of SHI to avoid having the manual step of importing and updating the host.template.yml.


Speaking to the biggest changes in the latest version of demo-tasks, Most of it was linting, this was my first time linting Ansible, and I do apologize for so many changes, but it was my attempt to get to using best practices from the get-go. 

The biggest change was in role names, most of it was from using "-" to "_" (dashes to underscores) as Ansible Galaxy Roles, which are highly modularized roles, require in the latest versions and future versions of Ansible to function properly and I envision all the roles as being lego like bricks instead of a monolithic package for the use outside of SHI. 

The other biggest change was in the networking, in Horizon View Environments and other Virtualized Environments, have a sub paravirtualized nics, in bridged mode, just don't work. As a result, internal NAT'ing is required. For most, and for now, the port forward sections can be ignored/removed.

**Comment by MarkProminic** [comment]
Here is a draft of what I am going to be including in into the Hosts.template.yml

https://github.com/DominoVagrant/demo-tasks/blob/release-please--branches--main--components--demo-tasks/Hosts.template.yml

**Comment by piotrzarzycki21** [comment]
I have moved hashes to separate class [SuperHumanHashes](https://github.com/Moonshine-IDE/Super.Human.Installer/blob/development/Source/superhuman/config/SuperHumanHashes.hx) and added missing hashes for nomad web 1.0.8. Next I will work on upgrade to newest demo-task.

**Comment by JoelProminic** [comment]
@MarkProminic, please take a look at the latest [development release](https://github.com/Moonshine-IDE/Super.Human.Installer/releases/tag/0.8.17-dev) when you have a chance and make sure this has the features you expect for 0.1.20.  

@piotrzarzycki21 reported that some files needed to be excluded when copying from demo-tasks to Super.Human.Installer, like Hosts.yml (not the template), .github and other Git properties, etc.  If you end up generating a ZIP template as part of the release, then these files should be excluded.   You can see the copied files [here](https://github.com/Moonshine-IDE/Super.Human.Installer/tree/development/Assets/provisioners/demo-tasks/0.1.20).  @piotrzarzycki21, please update this issue if you have a full list of the excluded files.

**Comment by JoelProminic** [comment]
I did a test with SHI 0.8.17 and demo-tasks 0.1.20.  I found that I was able to create an instance with all installers and a Domino FixPack configured.  

I tested on the same version that Piotr and Justin tested this morning, but I did not get a crash in my case.  Looking at the commit, it seems that the difference was that I had set all of the installers.

I did some comparson between the old and new VMs.  The `VBoxManage showvminfo` configuration showed no major differences.  I see the RAM changed from 16G to 8G, but I think I had increased it for the old VM.  

For Hosts.yml, the differences looked reasonable, based on my previous comparison.  I see that most of the versions were populated as expected, except for `domino_fixpack_version`.
